---
- name: Ensure Nginx is installed
  apt:
    name: nginx
    state: present
 
- name: Ensure Nginx is running
  systemd:
    name: nginx
    state: started
    enabled: true
 
- name: Create the document root directory for the virtual host
  file:
    path: "/var/www/{{ inventory_hostname }}"
    state: directory
    owner: www-data
    group: www-data
    mode: '0755'
 
- name: Create SSL directory
  file:
    path: /etc/nginx/ssl
    state: directory
    mode: '0755'
 
- name: Copy SSL certificate
  copy:
    src: ~/certs/wp.techbull.cloud/wp.techbull.cloud.pem
    dest: /etc/nginx/ssl/wp.techbull.cloud.pem
    owner: root
    group: root
    mode: '0644'
 
- name: Copy SSL key
  copy:
    src: ~/certs/wp.techbull.cloud/wp.techbull.cloud-key.pem
    dest: /etc/nginx/ssl/wp.techbull.cloud-key.pem
    owner: root
    group: root
    mode: '0600'

- name: Copy nginx conf
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    backup: no
    owner: root
    group: root
    mode: '0644'
  loop:
    - { src: roles/nginx/files/nginx.conf, dest: /etc/nginx/nginx.conf }
 
- name: Copy Virtual Host conf
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    backup: no
    owner: root
    group: root
    mode: '0644'
  loop:
    - { src: "{{ inventory_hostname }}.conf.j2", dest: "/etc/nginx/conf.d/{{ inventory_hostname }}.conf" }
  notify: restart nginx